import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type http from "node:http";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => {
  const createLLMProvider = vi.fn(() => ({
    chat: vi.fn(async (messages: Array<{ content: unknown }>) => {
      const system = String(messages[0]?.content ?? "");
      let text = JSON.stringify({ ok: true });
      if (system.includes("Cateo planning")) {
        text = JSON.stringify({
          taskClass: "inspection",
          objective: "Inspect the asset and produce controlled artifacts.",
          evidencePlan: ["Review the attachment evidence."],
          assumptions: ["The supplied asset metadata is correct."],
          risks: ["Do not approve release without objective evidence."],
          decisionBasis: ["Use measured observations and work-order context."],
          artifactPriorities: ["inspection-checklist", "service-report", "diagnostic-reasoning-log"],
          maintenanceConsiderations: ["Tie the result to the work order."],
          partsConsiderations: [],
        });
      } else if (system.includes("alternateHypotheses")) {
        text = JSON.stringify({
          alternateHypotheses: ["No competing failure mode identified."],
          blindSpots: ["Need operator confirmation of the reported condition."],
          missingAssumptions: [],
          evidenceGaps: [],
          recommendedAdjustments: ["Keep traceability on all observations."],
        });
      } else if (system.includes("artifactPlans")) {
        text = JSON.stringify({
          artifactPlans: [
            {
              artifactType: "inspection-checklist",
              title: "Inspection checklist",
              sectionOrder: ["objective", "checkpoints", "acceptance"],
              qualityGates: ["Schema valid"],
              requiredEvidence: ["Attachment evidence"],
            },
          ],
        });
      } else if (system.includes("executiveSummary")) {
        text = JSON.stringify({
          executiveSummary: "Prepared a controlled inspection artifact.",
          decision: "draft",
          confidence: "medium",
          rootCauseStatement: "Further review required.",
          nextActions: ["Route to review."],
          operatorNotes: ["Generated by the site bridge test."],
        });
      }
      return {
        content: [{ type: "text", text }],
        stopReason: "end_turn",
        usage: { inputTokens: 10, outputTokens: 20 },
      };
    }),
  }));

  return { createLLMProvider };
});

vi.mock("../src/llm/index.js", () => ({ createLLMProvider: mocks.createLLMProvider }));
vi.mock("../src/security/secure_store.js", async () => {
  const fsModule = await import("node:fs");
  const pathModule = await import("node:path");
  function ensureDir(filePath: string): void { fsModule.mkdirSync(pathModule.dirname(filePath), { recursive: true }); }
  function secretPath(name: string): string {
    const root = process.env.CATEO_HOME ?? process.cwd();
    return pathModule.join(root, "security", `${name.replace(/[^a-zA-Z0-9._-]/g, "_")}.secret`);
  }
  return {
    resetSecureStoreCache: () => undefined,
    writeProtectedText: (filePath: string, text: string) => { ensureDir(filePath); fsModule.writeFileSync(filePath, text, "utf-8"); },
    readProtectedText: (filePath: string) => fsModule.existsSync(filePath) ? fsModule.readFileSync(filePath, "utf-8") : null,
    writeProtectedJson: (filePath: string, data: unknown) => { ensureDir(filePath); fsModule.writeFileSync(filePath, JSON.stringify(data, null, 2), "utf-8"); },
    readProtectedJson: (filePath: string, fallback: unknown) => fsModule.existsSync(filePath) ? JSON.parse(fsModule.readFileSync(filePath, "utf-8")) : fallback,
    appendProtectedText: (filePath: string, text: string) => { ensureDir(filePath); fsModule.appendFileSync(filePath, text, "utf-8"); },
    removeProtectedFile: (filePath: string) => { if (fsModule.existsSync(filePath)) fsModule.unlinkSync(filePath); },
    writeProtectedSecret: (name: string, value: string) => { const filePath = secretPath(name); ensureDir(filePath); fsModule.writeFileSync(filePath, value, "utf-8"); },
    readProtectedSecret: (name: string) => { const filePath = secretPath(name); return fsModule.existsSync(filePath) ? fsModule.readFileSync(filePath, "utf-8") : undefined; },
    deleteProtectedSecret: (name: string) => { const filePath = secretPath(name); if (fsModule.existsSync(filePath)) fsModule.unlinkSync(filePath); },
  };
});

function randomPort(): number { return 48000 + Math.floor(Math.random() * 1000); }
async function closeServer(server: http.Server | null): Promise<void> { if (!server) return; await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }

async function bootBridge(): Promise<{ server: http.Server; baseUrl: string }> {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "cateo-site-bridge-"));
  const port = randomPort();
  process.env.CATEO_HOME = home;
  process.env.CATEO_SITE_PORT = String(port);
  process.env.CATEO_INTERNAL_TOKEN = "cateo-site-bridge-token";
  vi.resetModules();
  const { saveConfig } = await import("../src/config.js");
  saveConfig({
    agentId: "agent-1",
    llm: { provider: "ollama", model: "qwen3:8b", baseUrl: "http://localhost:11434/v1" },
    polling: { intervalMs: 30000, urgentIntervalMs: 10000 },
    pricing: { strategy: "fixed", baseRateEth: "0.005", maxRateEth: "0.05" },
    specialties: ["inspection"],
    autoQuote: false,
    autoWork: false,
    maxConcurrentTasks: 1,
    maxLoopTurns: 8,
    declineKeywords: [],
    learningEnabled: false,
    studyIntervalMs: 1800000,
    agentCashEnabled: false,
    security: {
      approvalPolicy: { quotes: true, declines: true, clientMessages: true, submissions: true, bountyClaims: true, agentCash: true },
      persistence: { persistOperatorChat: true, persistKnowledge: true, persistFeedback: true, persistDatasets: true, persistActivityLog: true, auditRetentionDays: 180 },
      agentCashPolicy: { maxUsdPerCall: 0.05, maxUsdPerTask: 0.25, allowedClasses: ["research", "social"] },
    },
    orchestration: {
      enabled: true,
      lead: { model: "qwen3:8b", baseUrl: "http://localhost:11434/v1" },
      challenger: { enabled: true, mode: "adaptive", model: "llama3.3", baseUrl: "http://localhost:11434/v1" },
      structure: { enabled: true, mode: "adaptive", model: "qwen2.5-coder:14b", baseUrl: "http://localhost:11434/v1" },
    },
  });
  const { startCateoSiteBridge } = await import("../src/cateo/site_server.js");
  const server = await startCateoSiteBridge();
  return { server, baseUrl: `http://127.0.0.1:${port}` };
}

describe("Cateo site bridge", () => {
  let server: http.Server | null = null;
  let baseUrl = "";

  beforeEach(() => { mocks.createLLMProvider.mockClear(); });
  afterEach(async () => {
    await closeServer(server);
    server = null;
    baseUrl = "";
    if (process.env.CATEO_HOME && fs.existsSync(process.env.CATEO_HOME)) fs.rmSync(process.env.CATEO_HOME, { recursive: true, force: true });
    delete process.env.CATEO_HOME;
    delete process.env.CATEO_SITE_PORT;
    delete process.env.CATEO_INTERNAL_TOKEN;
    vi.resetModules();
  });

  it("serves only the authenticated Cateo internal API surface", async () => {
    ({ server, baseUrl } = await bootBridge());
    const health = await fetch(`${baseUrl}/healthz`);
    expect(health.status).toBe(200);

    const denied = await fetch(`${baseUrl}/internal/cateo/health`);
    expect(denied.status).toBe(403);

    const hidden = await fetch(`${baseUrl}/api/bootstrap`);
    expect(hidden.status).toBe(404);

    const allowed = await fetch(`${baseUrl}/internal/cateo/health`, { headers: { Authorization: "Bearer cateo-site-bridge-token" } });
    expect(allowed.status).toBe(200);
  });

  it("queues and completes async assist jobs through the authenticated bridge", async () => {
    ({ server, baseUrl } = await bootBridge());
    const submit = await fetch(`${baseUrl}/internal/cateo/jobs/assist`, {
      method: "POST",
      headers: { Authorization: "Bearer cateo-site-bridge-token", "Content-Type": "application/json" },
      body: JSON.stringify({
        title: "Inspection request",
        symptomDescription: "Customer needs a controlled inspection artifact.",
        asset: { assetId: "A-100", model: "Rig-X" },
        workOrder: { workOrderId: "WO-100" },
      }),
    });

    expect(submit.status).toBe(202);
    const job = await submit.json() as { jobId: string; status: string };
    expect(job.jobId).toBeTruthy();
    expect(["queued", "running"]).toContain(job.status);

    let result: { status: string; result?: { summary: string; artifacts: Array<{ artifactType: string }> } } | null = null;
    for (let attempt = 0; attempt < 20; attempt += 1) {
      const poll = await fetch(`${baseUrl}/internal/cateo/jobs/assist/${job.jobId}`, {
        headers: { Authorization: "Bearer cateo-site-bridge-token" },
      });
      expect(poll.status).toBe(200);
      result = await poll.json() as { status: string; result?: { summary: string; artifacts: Array<{ artifactType: string }> } };
      if (result.status === "completed") {
        break;
      }
      await new Promise((resolve) => setTimeout(resolve, 10));
    }

    expect(result?.status).toBe("completed");
    expect(result?.result?.summary).toContain("Prepared");
    expect(result?.result?.artifacts[0]?.artifactType).toBe("inspection-checklist");
  });
});
