import http from "node:http";
import type { CashClawConfig } from "../config.js";
import { readRequestBody } from "../system/request_body.js";
import { buildCommandCenterSnapshot } from "./metrics.js";
import { CateoPublicAuthError, getPublicSession, listPublicUsers, loginPublicUser, logoutPublicSession, registerPublicUser } from "./accounts.js";
import { adoptRequesterConversations, completeConversationTurn, createConversationShare, failConversationTurn, getSharedConversation, listConversationSummaries, loadConversationRecord, queueConversationTurn, setConversationSaved, updateConversationCheckpoint } from "./conversations.js";
import { transcribeAudioWithOpenAI } from "./openai_media.js";
import { getAssistJob } from "./site_jobs.js";

export const CATEO_SITE_PUBLIC_PREFIX = "/internal/cateo/site";
const USER_SESSION_HEADER = "x-cateo-user-session";
const MAX_BODY_BYTES = 20_971_520;
const MAX_USERS = 30;
const MAX_CONVERSATIONS = 40;

function json(res: http.ServerResponse, data: unknown, status = 200) { res.writeHead(status, { "Content-Type": "application/json" }); res.end(JSON.stringify(data)); }
async function readBody(req: http.IncomingMessage) { return readRequestBody(req, { maxBytes: MAX_BODY_BYTES }); }
function parseJson<T>(raw: string) { try { return JSON.parse(raw) as T; } catch { throw new Error("Invalid JSON"); } }
function userSessionId(req: http.IncomingMessage) { const raw = req.headers[USER_SESSION_HEADER]; return (Array.isArray(raw) ? raw[0] : raw)?.trim() || undefined; }
function isAdmin(session: Awaited<ReturnType<typeof getSession>>) { return Boolean(session?.user.roles.includes("admin")); }
async function getSession(config: CashClawConfig | null, req: http.IncomingMessage, requesterId: string | null, requestId: string) { return config ? getPublicSession(config, userSessionId(req), requesterId ?? undefined, requestId) : null; }
async function syncConversationJobs(conversationId: string, requesterId: string | null) { const record = loadConversationRecord(conversationId); if (!record) return null; if (!requesterId) return record; for (const message of record.messages.filter((entry) => entry.role === "assistant" && entry.jobId && (entry.status === "queued" || entry.status === "running"))) { const jobId = message.jobId; if (!jobId) continue; const job = getAssistJob(jobId, requesterId); if (!job) continue; const known = message.checkpoints.length; for (const checkpoint of job.checkpoints.slice(known)) { updateConversationCheckpoint({ conversationId, assistantMessageId: message.messageId, checkpoint }); } if (job.status === "completed" && job.result) { completeConversationTurn({ conversationId, assistantMessageId: message.messageId, result: job.result }); } else if (job.status === "failed") { failConversationTurn({ conversationId, assistantMessageId: message.messageId, error: job.error || "Cateo could not complete that request." }); } } return loadConversationRecord(conversationId); }

export async function handleCateoSitePublicApi(args: { pathname: string; req: http.IncomingMessage; res: http.ServerResponse; config: CashClawConfig | null; requestId: string; requesterId: string | null }): Promise<boolean> {
  const { pathname, req, res, config, requestId, requesterId } = args;
  if (!pathname.startsWith(CATEO_SITE_PUBLIC_PREFIX)) return false;
  if (!config) { json(res, { error: "Cateo runtime is not configured" }, 503); return true; }
  const session = await getSession(config, req, requesterId, requestId);
  const viewer = { requesterId: requesterId ?? undefined, userId: session?.user.userId, admin: isAdmin(session) };
  try {
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/auth/session`) { json(res, { ok: true, session }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/auth/register`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } if (!requesterId) { json(res, { error: "Missing or invalid X-Cateo-Client-Id" }, 400); return true; } const body = parseJson<{ email: string; password: string; displayName?: string; organization?: string; username?: string }>(await readBody(req)); const created = registerPublicUser(config, { ...body, requesterId }, requestId); adoptRequesterConversations(created.user.userId, requesterId, created.user.profileId); json(res, { ok: true, session: created }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/auth/login`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } if (!requesterId) { json(res, { error: "Missing or invalid X-Cateo-Client-Id" }, 400); return true; } const body = parseJson<{ identifier: string; password: string }>(await readBody(req)); const loggedIn = loginPublicUser(config, { ...body, requesterId }, requestId); adoptRequesterConversations(loggedIn.user.userId, requesterId, loggedIn.user.profileId); json(res, { ok: true, session: loggedIn }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/auth/logout`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } logoutPublicSession(userSessionId(req), requestId); json(res, { ok: true }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/conversations`) { if (req.method !== "GET") { json(res, { error: "GET only" }, 405); return true; } const items = listConversationSummaries(viewer).slice(0, MAX_CONVERSATIONS); const synced = []; for (const item of items) { const record = await syncConversationJobs(item.conversationId, requesterId); synced.push(record ? { ...item, pendingCount: record.messages.filter((m) => m.role === "assistant" && (m.status === "queued" || m.status === "running")).length, updatedAt: record.updatedAt, lastMessagePreview: record.lastMessagePreview, title: record.title, titleSource: record.titleSource, saved: record.saved, shareId: record.shareId, messageCount: record.messages.length } : item); } json(res, { ok: true, items: synced, session }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/conversations/queue-turn`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } if (!requesterId) { json(res, { error: "Missing or invalid X-Cateo-Client-Id" }, 400); return true; } const body = parseJson<{ conversationId?: string; jobId: string; promptText: string; input: import("./types.js").CateoAssistInput }>(await readBody(req)); const queued = queueConversationTurn({ conversationId: body.conversationId, viewer, requesterId, ownerUserId: session?.user.userId, profileId: session?.user.profileId, jobId: body.jobId, input: body.input, promptText: body.promptText }); json(res, { ok: true, conversation: queued.summary, assistantMessageId: queued.assistantMessage.messageId, userMessageId: queued.userMessage.messageId }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/conversations/sync-job`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } if (!requesterId) { json(res, { error: "Missing or invalid X-Cateo-Client-Id" }, 400); return true; } const body = parseJson<{ conversationId: string; assistantMessageId: string; jobId: string }>(await readBody(req)); const job = getAssistJob(body.jobId, requesterId); if (!job) { json(res, { error: "Job not found" }, 404); return true; } if (job.status === "completed" && job.result) completeConversationTurn({ conversationId: body.conversationId, assistantMessageId: body.assistantMessageId, result: job.result }); else if (job.status === "failed") failConversationTurn({ conversationId: body.conversationId, assistantMessageId: body.assistantMessageId, error: job.error || "Cateo could not complete that request." }); else for (const checkpoint of job.checkpoints) updateConversationCheckpoint({ conversationId: body.conversationId, assistantMessageId: body.assistantMessageId, checkpoint }); json(res, { ok: true, conversation: loadConversationRecord(body.conversationId) }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/admin/overview`) { if (req.method !== "GET") { json(res, { error: "GET only" }, 405); return true; } if (!isAdmin(session)) { json(res, { error: "Admin access required" }, 403); return true; } json(res, { ok: true, metrics: buildCommandCenterSnapshot(), users: listPublicUsers(config).slice(0, MAX_USERS), conversations: listConversationSummaries({ admin: true }).slice(0, MAX_CONVERSATIONS), session }); return true; }
    if (pathname === `${CATEO_SITE_PUBLIC_PREFIX}/transcribe`) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } if (!requesterId) { json(res, { error: "Missing or invalid X-Cateo-Client-Id" }, 400); return true; } const body = parseJson<{ name?: string; mimeType?: string; contentBase64: string }>(await readBody(req)); const transcript = await transcribeAudioWithOpenAI(config, { ...body, requesterId }, requestId); json(res, { ok: true, transcript, session }); return true; }

    const conversationMatch = pathname.match(/^\/internal\/cateo\/site\/conversations\/([^/]+)$/);
    if (conversationMatch) { if (req.method !== "GET") { json(res, { error: "GET only" }, 405); return true; } const conversation = await syncConversationJobs(decodeURIComponent(conversationMatch[1]), requesterId); if (!conversation || !canAccess(conversation, viewer)) { json(res, { error: "Conversation not found" }, 404); return true; } json(res, { ok: true, conversation, session }); return true; }
    const saveMatch = pathname.match(/^\/internal\/cateo\/site\/conversations\/([^/]+)\/save$/);
    if (saveMatch) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } const body = parseJson<{ saved: boolean }>(await readBody(req)); const conversation = setConversationSaved(decodeURIComponent(saveMatch[1]), viewer, !!body.saved); json(res, { ok: true, conversation }); return true; }
    const shareMatch = pathname.match(/^\/internal\/cateo\/site\/conversations\/([^/]+)\/share$/);
    if (shareMatch) { if (req.method !== "POST") { json(res, { error: "POST only" }, 405); return true; } const share = createConversationShare(decodeURIComponent(shareMatch[1]), viewer); json(res, { ok: true, shareId: share.shareId, token: share.token, conversation: share.conversation }); return true; }
    const sharedMatch = pathname.match(/^\/internal\/cateo\/site\/shared\/([^/]+)$/);
    if (sharedMatch) { if (req.method !== "GET") { json(res, { error: "GET only" }, 405); return true; } const conversation = getSharedConversation(decodeURIComponent(sharedMatch[1])); if (!conversation) { json(res, { error: "Shared conversation not found" }, 404); return true; } json(res, { ok: true, conversation }); return true; }
  } catch (error) {
    if (error instanceof CateoPublicAuthError) { json(res, { error: error.message, code: error.code }, error.status); return true; }
    json(res, { error: error instanceof Error ? error.message : "Internal server error" }, 500); return true;
  }
  return false;
}
function canAccess(conversation: NonNullable<ReturnType<typeof loadConversationRecord>>, viewer: { requesterId?: string; userId?: string; admin?: boolean }) { if (viewer.admin) return true; if (viewer.userId) return conversation.ownerUserId === viewer.userId || (!conversation.ownerUserId && viewer.requesterId && conversation.requesterId === viewer.requesterId); return Boolean(viewer.requesterId && conversation.requesterId === viewer.requesterId); }

