import type { CateoArtifactRecord, CateoConfidence, CateoDiagnosticReasoningLog, CateoInspectionChecklist, CateoInteractionProjection, CateoPartsToolsList, CateoServiceReport, CateoTroubleshootingProcedure } from "./types.js";
import { deriveConversationTitleFromArtifacts } from "./artifact_metadata.js";

const RENDERER_VERSION = "cateo-renderer-v2";
const unique = (values: Array<string | undefined | null>) => [...new Set(values.map((v) => v?.trim()).filter((v): v is string => Boolean(v)))];
const latest = (record: CateoArtifactRecord) => record.revisions[record.revisions.length - 1];
function label(artifactType: CateoArtifactRecord["artifactType"]) { switch (artifactType) { case "troubleshooting-procedure": return "troubleshooting procedure"; case "inspection-checklist": return "inspection checklist"; case "service-report": return "service report"; case "parts-tools-list": return "parts and tools list"; case "diagnostic-reasoning-log": return "diagnostic reasoning log"; default: return artifactType; } }
function find<T>(artifacts: CateoArtifactRecord[], artifactType: CateoArtifactRecord["artifactType"]) { const match = artifacts.find((artifact) => artifact.artifactType === artifactType); return match ? latest(match).content as T : null; }
function rootCause(reasoning: CateoDiagnosticReasoningLog | null, procedure: CateoTroubleshootingProcedure | null, report: CateoServiceReport | null) { if (reasoning?.rootCauseStatement) return reasoning.rootCauseStatement; if (report?.summary) return report.summary; if (procedure?.objective) return procedure.objective; return "Cateo prepared a controlled engineering response package from the submitted evidence."; }
function pathSummary(checklist: CateoInspectionChecklist | null, procedure: CateoTroubleshootingProcedure | null) { if (procedure?.steps?.length) { const step = procedure.steps[0]; return step ? `${step.action} Expected outcome: ${step.expectedResult}.` : "Start with the first controlled verification step."; } if (checklist?.checklist?.length) { const item = checklist.checklist[0]; return item ? `${item.check} Pass criteria: ${item.passCriteria}.` : "Begin with the first checklist item."; } return "Follow the controlled verification flow captured in the artifact package."; }
function partSummary(parts: CateoPartsToolsList | null) { if (!parts || parts.parts.length === 0) return null; return `If replacement material is needed, start with ${parts.parts.slice(0, 2).map((p) => `${p.sku} ${p.description}`.trim()).join(", ")}.`; }
export function renderCateoInteraction(artifacts: CateoArtifactRecord[]): CateoInteractionProjection { const reasoning = find<CateoDiagnosticReasoningLog>(artifacts, "diagnostic-reasoning-log"); const procedure = find<CateoTroubleshootingProcedure>(artifacts, "troubleshooting-procedure"); const report = find<CateoServiceReport>(artifacts, "service-report"); const checklist = find<CateoInspectionChecklist>(artifacts, "inspection-checklist"); const parts = find<CateoPartsToolsList>(artifacts, "parts-tools-list"); const cause = rootCause(reasoning, procedure, report); const start = pathSummary(checklist, procedure); const partsText = partSummary(parts); const nextActions = unique([...(procedure?.followUpActions ?? []), ...(report?.recommendations ?? []), ...(reasoning?.evidenceRequests ?? []), ...(checklist?.completionCriteria ?? [])]).slice(0, 5); const highlights = unique([report?.summary, cause, checklist?.completionCriteria?.[0], procedure?.acceptanceCriteria?.[0], partsText]).slice(0, 5); const actionSentence = nextActions.length ? `Recommended next steps: ${nextActions.slice(0, 3).map((entry, index) => `${index + 1}. ${entry}`).join(" ")}` : null; return { message: [`Here is the current engineering read: ${cause}`, `Start here: ${start}`, actionSentence, partsText].filter(Boolean).join("\n\n"), highlights, nextActions, confidence: reasoning?.confidence ?? "medium" as CateoConfidence, artifactCount: artifacts.length, artifactLabels: artifacts.map((artifact) => label(artifact.artifactType)), conversationTitle: deriveConversationTitleFromArtifacts(artifacts), releaseStatus: "available", renderedAt: new Date().toISOString(), rendererVersion: RENDERER_VERSION }; }
export function renderArtifactSearchText(record: CateoArtifactRecord) { const revision = latest(record); return [label(record.artifactType), revision.summary, JSON.stringify(revision.metadata ?? {}), JSON.stringify(revision.content), record.assetId, record.workOrderId].filter(Boolean).join("\n"); }
